apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: container-crash
  namespace: litmus
spec:
  engineState: "active"
  annotationCheck: "false"
  appinfo:
    appns: "demo"
    applabel: "component=podtato-head-entry"
    appkind: "deployment"
  chaosServiceAccount: litmus-admin
  experiments:
  - name: container-kill
    spec:
      components:
        env:
        - name: TOTAL_CHAOS_DURATION
          value: '60'
        - name: CHAOS_INTERVAL
          value: '10'
        - name: CONTAINER_RUNTIME
          value: docker
        - name: SOCKET_PATH
          value: /var/run/docker.sock
        - name: PODS_AFFECTED_PERC
          value: ""
        - name: TARGET_CONTAINER
          value: ""
