
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: slow-podtato
  namespace: litmus
spec:
  engineState: "active"
  annotationCheck: "false"
  appinfo:
    appns: "demo"
    applabel: "component=podtato-head-entry"
    appkind: "deployment"
  chaosServiceAccount: litmus-admin
  experiments:
  - name: pod-network-latency
    spec:
      components:
        env:
        # network latency to be injected
        - name: NETWORK_LATENCY
          value: '5000' #in ms
        - name: TOTAL_CHAOS_DURATION
          value: '60'
        - name: CONTAINER_RUNTIME
          value: docker
        - name: SOCKET_PATH
          value: /var/run/docker.sock
        - name: PODS_AFFECTED_PERC
          value: ""
