
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: replica-delete
  namespace: litmus
spec:
  engineState: "active"
  annotationCheck: "false"
  appinfo:
    appns: "demo"
    applabel: "app=helloservice"
    appkind: "deployment"
  chaosServiceAccount: litmus-admin
  experiments:
  - name: pod-delete
    spec:
      components:
        env:
        - name: TOTAL_CHAOS_DURATION
          value: '10'
        - name: CHAOS_INTERVAL
          value: '10'
        - name: PODS_AFFECTED_PERC
          value: ""
        
